spring.application.name=arena

spring.datasource.url=jdbc:mysql://localhost:3306/csjmu_arena
spring.datasource.username=root
spring.datasource.password=P@ssword970

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=7f4a9c3e8b1d6f2a5c9e4b7d8f1a3c6b9e2f5a8d1c4b7e9f2a6c3d8b1e5f9a7
jwt.expiration=86400000